export const getDefaultInvoiceFormData = () => ({
  invoice_type: 'INCOMING_SUPPLIER' as 'INCOMING_SUPPLIER' | 'INCOMING_INVESTMENT' | 'OUTGOING_SUPPLIER' | 'OUTGOING_SALES' | 'INCOMING_OFFICE' | 'OUTGOING_OFFICE' | 'INCOMING_BANK' | 'OUTGOING_BANK',
  company_id: '',
  supplier_id: '',
  office_supplier_id: '',
  customer_id: '',
  bank_id: '',
  apartment_id: '',
  contract_id: '',
  milestone_id: '',
  invoice_number: '',
  reference_number: '',
  iban: '',
  issue_date: new Date().toISOString().split('T')[0],
  due_date: '',
  base_amount: 0,
  vat_rate: 25,
  base_amount_1: 0,
  base_amount_2: 0,
  base_amount_3: 0,
  base_amount_4: 0,
  category: '',
  project_id: '',
  refund_id: '',
  description: ''
})

export const getDefaultPaymentFormData = () => ({
  payment_source_type: 'bank_account' as 'bank_account' | 'credit',
  company_bank_account_id: '',
  credit_id: '',
  credit_allocation_id: '',
  is_cesija: false,
  cesija_company_id: '',
  cesija_bank_account_id: '',
  cesija_credit_id: '',
  cesija_credit_allocation_id: '',
  payment_date: new Date().toISOString().split('T')[0],
  amount: 0,
  payment_method: 'WIRE' as 'WIRE' | 'CASH' | 'CHECK' | 'CARD',
  reference_number: '',
  description: ''
})
