/*\n  # Add buildings, garages, and repositories tables\n\n  ## Overview\n  This migration adds hierarchical structure for real estate projects:\n  - Buildings can contain apartments, garages, and repositories\n  - Apartments can be linked to garages and repositories\n  \n  ## New Tables\n  \n  ### `buildings`\n  - `id` (uuid, primary key)\n  - `project_id` (uuid, foreign key to projects)\n  - `name` (text) - Building name/number\n  - `description` (text, optional) - Additional details\n  - `total_floors` (integer) - Number of floors\n  - `created_at` (timestamptz)\n  \n  ### `garages`\n  - `id` (uuid, primary key)\n  - `building_id` (uuid, foreign key to buildings)\n  - `number` (text) - Garage number/identifier\n  - `floor` (integer) - Floor location\n  - `size_m2` (numeric) - Size in square meters\n  - `price` (numeric) - Price\n  - `status` (text) - Available/Reserved/Sold\n  - `buyer_name` (text, optional) - Buyer name if sold\n  - `created_at` (timestamptz)\n  \n  ### `repositories`\n  - `id` (uuid, primary key)\n  - `building_id` (uuid, foreign key to buildings)\n  - `number` (text) - Repository number/identifier\n  - `floor` (integer) - Floor location\n  - `size_m2` (numeric) - Size in square meters\n  - `price` (numeric) - Price\n  - `status` (text) - Available/Reserved/Sold\n  - `buyer_name` (text, optional) - Buyer name if sold\n  - `created_at` (timestamptz)\n  \n  ## Table Modifications\n  \n  ### `apartments`\n  - Add `building_id` (uuid, foreign key to buildings)\n  - Add `garage_id` (uuid, nullable, foreign key to garages) - Linked garage\n  - Add `repository_id` (uuid, nullable, foreign key to repositories) - Linked repository\n  \n  ## Security\n  - Enable RLS on all new tables\n  - Add policies for authenticated users to manage their data\n*/\n\n-- Create buildings table\nCREATE TABLE IF NOT EXISTS buildings (\n  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),\n  project_id uuid NOT NULL REFERENCES projects(id) ON DELETE CASCADE,\n  name text NOT NULL,\n  description text DEFAULT '',\n  total_floors integer NOT NULL DEFAULT 1,\n  created_at timestamptz DEFAULT now()\n)
\n\n-- Create garages table\nCREATE TABLE IF NOT EXISTS garages (\n  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),\n  building_id uuid NOT NULL REFERENCES buildings(id) ON DELETE CASCADE,\n  number text NOT NULL,\n  floor integer NOT NULL DEFAULT 0,\n  size_m2 numeric NOT NULL DEFAULT 0,\n  price numeric NOT NULL DEFAULT 0,\n  status text NOT NULL DEFAULT 'Available',\n  buyer_name text,\n  created_at timestamptz DEFAULT now(),\n  CONSTRAINT garages_status_check CHECK (status IN ('Available', 'Reserved', 'Sold'))\n)
\n\n-- Create repositories table\nCREATE TABLE IF NOT EXISTS repositories (\n  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),\n  building_id uuid NOT NULL REFERENCES buildings(id) ON DELETE CASCADE,\n  number text NOT NULL,\n  floor integer NOT NULL DEFAULT 0,\n  size_m2 numeric NOT NULL DEFAULT 0,\n  price numeric NOT NULL DEFAULT 0,\n  status text NOT NULL DEFAULT 'Available',\n  buyer_name text,\n  created_at timestamptz DEFAULT now(),\n  CONSTRAINT repositories_status_check CHECK (status IN ('Available', 'Reserved', 'Sold'))\n)
\n\n-- Add building_id to apartments if it doesn't exist\nDO $$\nBEGIN\n  IF NOT EXISTS (\n    SELECT 1 FROM information_schema.columns\n    WHERE table_name = 'apartments' AND column_name = 'building_id'\n  ) THEN\n    ALTER TABLE apartments ADD COLUMN building_id uuid REFERENCES buildings(id) ON DELETE CASCADE
\n  END IF
\nEND $$
\n\n-- Add garage_id to apartments if it doesn't exist\nDO $$\nBEGIN\n  IF NOT EXISTS (\n    SELECT 1 FROM information_schema.columns\n    WHERE table_name = 'apartments' AND column_name = 'garage_id'\n  ) THEN\n    ALTER TABLE apartments ADD COLUMN garage_id uuid REFERENCES garages(id) ON DELETE SET NULL
\n  END IF
\nEND $$
\n\n-- Add repository_id to apartments if it doesn't exist\nDO $$\nBEGIN\n  IF NOT EXISTS (\n    SELECT 1 FROM information_schema.columns\n    WHERE table_name = 'apartments' AND column_name = 'repository_id'\n  ) THEN\n    ALTER TABLE apartments ADD COLUMN repository_id uuid REFERENCES repositories(id) ON DELETE SET NULL
\n  END IF
\nEND $$
\n\n-- Enable RLS\nALTER TABLE buildings ENABLE ROW LEVEL SECURITY
\nALTER TABLE garages ENABLE ROW LEVEL SECURITY
\nALTER TABLE repositories ENABLE ROW LEVEL SECURITY
\n\n-- RLS Policies for buildings\nCREATE POLICY "Authenticated users can view buildings"\n  ON buildings FOR SELECT\n  TO authenticated\n  USING (true)
\n\nCREATE POLICY "Authenticated users can insert buildings"\n  ON buildings FOR INSERT\n  TO authenticated\n  WITH CHECK (true)
\n\nCREATE POLICY "Authenticated users can update buildings"\n  ON buildings FOR UPDATE\n  TO authenticated\n  USING (true)\n  WITH CHECK (true)
\n\nCREATE POLICY "Authenticated users can delete buildings"\n  ON buildings FOR DELETE\n  TO authenticated\n  USING (true)
\n\n-- RLS Policies for garages\nCREATE POLICY "Authenticated users can view garages"\n  ON garages FOR SELECT\n  TO authenticated\n  USING (true)
\n\nCREATE POLICY "Authenticated users can insert garages"\n  ON garages FOR INSERT\n  TO authenticated\n  WITH CHECK (true)
\n\nCREATE POLICY "Authenticated users can update garages"\n  ON garages FOR UPDATE\n  TO authenticated\n  USING (true)\n  WITH CHECK (true)
\n\nCREATE POLICY "Authenticated users can delete garages"\n  ON garages FOR DELETE\n  TO authenticated\n  USING (true)
\n\n-- RLS Policies for repositories\nCREATE POLICY "Authenticated users can view repositories"\n  ON repositories FOR SELECT\n  TO authenticated\n  USING (true)
\n\nCREATE POLICY "Authenticated users can insert repositories"\n  ON repositories FOR INSERT\n  TO authenticated\n  WITH CHECK (true)
\n\nCREATE POLICY "Authenticated users can update repositories"\n  ON repositories FOR UPDATE\n  TO authenticated\n  USING (true)\n  WITH CHECK (true)
\n\nCREATE POLICY "Authenticated users can delete repositories"\n  ON repositories FOR DELETE\n  TO authenticated\n  USING (true)