-- Migration 20251116124513: original content removed during history reconciliation.
-- Original content: Test PM user for Kozara project
-- Reason: Seed/test data not needed for replay in fresh environments.
-- Original SQL is preserved in git history.
-- This file is intentionally a no-op.
