-- contract_types.id was a bare integer PK with no sequence/identity, forcing a racy
-- client-side max(id)+1 that collided on the PK under concurrent category creation.
-- Convert to an identity column so Postgres assigns ids, then seed the sequence past
-- the current max so existing rows don't collide with future inserts.

ALTER TABLE public.contract_types
    ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

SELECT setval(
    pg_get_serial_sequence('public.contract_types', 'id'),
    COALESCE((SELECT MAX(id) FROM public.contract_types), 0) + 1,
    false
);
