-- Migration 20260417180001: original content superseded by baseline.
-- Original SQL preserved in git history before the baseline reconciliation commit.
-- This file is intentionally a no-op for fresh-environment replay.
