-- Splits the conflated `project_phases.phase_name` field into two independent axes:
--
--   * project_phases.phase_name  -> a REAL phase name ("Faza 1", "Foundation Phase")
--   * cost_classifications       -> the cost breakdown bucket a contract belongs to
--                                   ("Zemljiste", "Priprema i razvoj", ...)
--
-- Until now users typed the cost classification into `phase_name`, which meant a project
-- could never have more than one real phase and the seven canonical bucket names drifted
-- into 17 distinct spellings (casing, word order, synonyms, stray whitespace).
--
-- `contracts.contract_type_id` is UNAFFECTED and stays as a third, orthogonal axis
-- underneath the classification (Razno / Rusenje / Javni biljeznici).
--
-- The data migration that folds today's classification-shaped phase rows into this model
-- is 20260908120200_split_phase_classification.sql. Apply both together.

-- ---------------------------------------------------------------- cost_classifications

CREATE TABLE public.cost_classifications (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        text UNIQUE,
    name        text NOT NULL UNIQUE,
    description text,
    sort_order  integer NOT NULL DEFAULT 0,
    is_system   boolean NOT NULL DEFAULT false,
    is_active   boolean NOT NULL DEFAULT true,
    created_at  timestamptz NOT NULL DEFAULT now(),
    updated_at  timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT cost_classifications_name_not_blank CHECK (btrim(name) <> ''),
    CONSTRAINT cost_classifications_system_has_code CHECK (NOT is_system OR code IS NOT NULL)
);

COMMENT ON TABLE public.cost_classifications IS
  'Global cost breakdown categories used to group contracts inside a project phase. '
  'is_system rows are seeded and may not be renamed or deleted. Orthogonal to contract_types.';
COMMENT ON COLUMN public.cost_classifications.code IS
  'Stable slug for seeded rows; NULL for user-created rows. Never shown to users -- it exists '
  'so migrations, assertions and tests can reference a bucket without a Croatian display string.';

-- integer identity PK deliberately mirrors contract_types (see 20260616120100), so the two
-- lookups stay structurally identical in the TS types and the two form selects.

CREATE TRIGGER update_cost_classifications_updated_at
    BEFORE UPDATE ON public.cost_classifications
    FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

-- The canonical seven. These are Croatian domain terms and are NEVER translated
-- (CLAUDE.md i18n rule 3) -- they live here as data, identical in every locale.
-- sort_order in tens so a user can slot a row in between without a renumber.
INSERT INTO public.cost_classifications (code, name, sort_order, is_system) VALUES
    ('zemljiste',             'Zemljište',             10, true),
    ('priprema_i_razvoj',     'Priprema i razvoj',     20, true),
    ('izgradnja_i_uredenje',  'Izgradnja i uređenje',  30, true),
    ('opremanje',             'Opremanje',             40, true),
    ('kontrola',              'Kontrola',              50, true),
    ('financiranje_i_nadzor', 'Financiranje i nadzor', 60, true),
    ('nepredvideni_troskovi', 'Nepredviđeni troškovi', 70, true);

-- Freeze the system rows in the DATABASE, not just the UI. RLS cannot express "this column
-- of this row is frozen", so without this trigger the guarantee is one `disabled` attribute
-- in React. is_active / sort_order / description stay editable so a company that never buys
-- land can hide "Zemljište" without deleting it.
CREATE OR REPLACE FUNCTION public.protect_system_cost_classifications()
RETURNS trigger
LANGUAGE plpgsql
SET search_path TO 'public'
AS $$
BEGIN
  IF TG_OP = 'DELETE' THEN
    IF OLD.is_system THEN
      RAISE EXCEPTION 'Sistemska klasifikacija troška se ne može obrisati'
        USING ERRCODE = 'restrict_violation';
    END IF;
    RETURN OLD;
  END IF;

  IF OLD.is_system AND (NEW.name      <>         OLD.name
                     OR NEW.code      IS DISTINCT FROM OLD.code
                     OR NEW.is_system <>         OLD.is_system) THEN
    RAISE EXCEPTION 'Sistemska klasifikacija troška se ne može preimenovati'
      USING ERRCODE = 'restrict_violation';
  END IF;

  RETURN NEW;
END $$;

CREATE TRIGGER trg_protect_system_cost_classifications
    BEFORE UPDATE OR DELETE ON public.cost_classifications
    FOR EACH ROW EXECUTE FUNCTION public.protect_system_cost_classifications();

-- ------------------------------------------------------------ contracts.classification_id

-- NULLABLE on purpose: Samobor's 5 and Tar's 32 contracts sit on phases whose names are real
-- phase names ("Foundation Phase", "Retroaktivno"), not classifications, so they legitimately
-- have no bucket. Repeating contract_type_id's `NOT NULL DEFAULT 0 -> nonexistent row` mistake
-- (fixed in 20260908120300) would be a regression.
--
-- No ON DELETE clause => NO ACTION, mirroring contracts_contract_type_id_fkey: a classification
-- that is in use cannot be deleted, users deactivate it instead.
ALTER TABLE public.contracts
    ADD COLUMN classification_id integer REFERENCES public.cost_classifications(id);

CREATE INDEX idx_contracts_classification_id
    ON public.contracts USING btree (classification_id);
CREATE INDEX idx_contracts_phase_classification
    ON public.contracts USING btree (phase_id, classification_id);

COMMENT ON COLUMN public.contracts.classification_id IS
  'Cost breakdown bucket within the phase. Orthogonal to contract_type_id. '
  'NULL means unclassified (legacy rows, or phases that are not cost-broken-down).';

-- ------------------------------------------------- phase_classification_budgets

-- Optional sub-allocation of a phase budget across classifications.
--
-- A row may exist with budget_allocated = 0 purely to pin an (empty) classification group into
-- a phase card -- that is how a user plans before any contract exists, and Funtana already does
-- exactly this (Opremanje budgeted at 812.401 with zero contracts).
--
-- Surrogate uuid PK rather than a composite (phase_id, classification_id) PK because
-- activity_logs.entity_id is uuid: with a composite key every budget edit would become a
-- metadata-only log entry, the same wart cost/contract type creation already has.
CREATE TABLE public.phase_classification_budgets (
    id                uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    phase_id          uuid NOT NULL REFERENCES public.project_phases(id) ON DELETE CASCADE,
    classification_id integer NOT NULL REFERENCES public.cost_classifications(id),
    budget_allocated  numeric(15,2) NOT NULL DEFAULT 0,
    notes             text,
    created_at        timestamptz NOT NULL DEFAULT now(),
    updated_at        timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT phase_classification_budgets_phase_classification_key
        UNIQUE (phase_id, classification_id),
    CONSTRAINT phase_classification_budgets_non_negative
        CHECK (budget_allocated >= 0)
);

CREATE INDEX idx_phase_classification_budgets_phase_id
    ON public.phase_classification_budgets USING btree (phase_id);

COMMENT ON TABLE public.phase_classification_budgets IS
  'Optional sub-allocation of project_phases.budget_allocated across cost classifications. '
  'The sum is intentionally NOT constrained to equal the phase budget -- sub-allocations are '
  'optional, so an unallocated remainder is a legitimate state, surfaced in the UI as '
  '"Neraspoređeno". A CHECK here would make the 20260908120200 data migration fail on the '
  'even-split budgets that most projects currently carry.';

CREATE TRIGGER update_phase_classification_budgets_updated_at
    BEFORE UPDATE ON public.phase_classification_budgets
    FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

-- ------------------------------------------------------------------------------ RLS

ALTER TABLE public.cost_classifications         ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.phase_classification_budgets ENABLE ROW LEVEL SECURITY;

-- cost_classifications mirrors the contract_types policy set verbatim (baseline :7706 insert,
-- :7883 update, :8069 select, :8613 delete). Note contract_types matches on lower(users.role)
-- while project_phases matches on the exact-case role -- each table below keeps the convention
-- of the table it is modelled on rather than inventing a third.

CREATE POLICY "Authenticated users can view cost classifications"
  ON public.cost_classifications FOR SELECT TO authenticated USING (true);

CREATE POLICY "Authenticated users can insert cost classifications"
  ON public.cost_classifications FOR INSERT TO authenticated
  WITH CHECK ((EXISTS ( SELECT 1
     FROM public.users
    WHERE ((users.auth_user_id = auth.uid()) AND (lower(users.role) = ANY (ARRAY['director'::text, 'admin'::text, 'project_manager'::text, 'supervision'::text]))))));

CREATE POLICY "Authenticated users can update cost classifications"
  ON public.cost_classifications FOR UPDATE TO authenticated
  USING ((EXISTS ( SELECT 1
     FROM public.users
    WHERE ((users.auth_user_id = auth.uid()) AND (lower(users.role) = ANY (ARRAY['director'::text, 'admin'::text, 'project_manager'::text, 'supervision'::text]))))))
  WITH CHECK ((EXISTS ( SELECT 1
     FROM public.users
    WHERE ((users.auth_user_id = auth.uid()) AND (lower(users.role) = ANY (ARRAY['director'::text, 'admin'::text, 'project_manager'::text, 'supervision'::text]))))));

CREATE POLICY "Directors can delete cost classifications"
  ON public.cost_classifications FOR DELETE TO authenticated
  USING ((EXISTS ( SELECT 1
     FROM public.users
    WHERE ((users.auth_user_id = auth.uid()) AND (lower(users.role) = ANY (ARRAY['director'::text, 'admin'::text]))))));

-- phase_classification_budgets mirrors the project_phases policy set (baseline :8366 insert,
-- :8384 update, :8514 delete, :8586 select, :9146 Supervision-scoped select), reaching the
-- project through project_phases.
--
-- NOTE: project_phases itself has no SELECT policy for Supervision users on projects they do
-- not manage, and its write policies are role-only rather than project-scoped. That is mirrored
-- here exactly rather than silently tightened; fixing both is a separate, deliberate change.

CREATE POLICY "Directors and general users can view all phase classification budgets"
  ON public.phase_classification_budgets FOR SELECT TO authenticated
  USING ((EXISTS ( SELECT 1
     FROM public.users
    WHERE ((users.auth_user_id = auth.uid()) AND (users.role = ANY (ARRAY['Director'::text, 'Investment'::text, 'Sales'::text, 'Accounting'::text]))))));

CREATE POLICY "Supervision users can view phase classification budgets from assigned projects"
  ON public.phase_classification_budgets FOR SELECT TO authenticated
  USING ((EXISTS ( SELECT 1
     FROM ((public.project_phases ph
       JOIN public.project_managers pm ON ((pm.project_id = ph.project_id)))
       JOIN public.users u ON ((pm.user_id = u.id)))
    WHERE ((ph.id = phase_classification_budgets.phase_id) AND (u.auth_user_id = auth.uid()) AND (u.role = 'Supervision'::text)))));

CREATE POLICY "Director and Supervision can insert phase classification budgets"
  ON public.phase_classification_budgets FOR INSERT TO authenticated
  WITH CHECK ((EXISTS ( SELECT 1
     FROM public.users
    WHERE ((users.auth_user_id = auth.uid()) AND (users.role = ANY (ARRAY['Director'::text, 'Supervision'::text]))))));

CREATE POLICY "Director and Supervision can update phase classification budgets"
  ON public.phase_classification_budgets FOR UPDATE TO authenticated
  USING ((EXISTS ( SELECT 1
     FROM public.users
    WHERE ((users.auth_user_id = auth.uid()) AND (users.role = ANY (ARRAY['Director'::text, 'Supervision'::text]))))))
  WITH CHECK ((EXISTS ( SELECT 1
     FROM public.users
    WHERE ((users.auth_user_id = auth.uid()) AND (users.role = ANY (ARRAY['Director'::text, 'Supervision'::text]))))));

CREATE POLICY "Director and Supervision can delete phase classification budgets"
  ON public.phase_classification_budgets FOR DELETE TO authenticated
  USING ((EXISTS ( SELECT 1
     FROM public.users
    WHERE ((users.auth_user_id = auth.uid()) AND (users.role = ANY (ARRAY['Director'::text, 'Supervision'::text]))))));
